kind: Deployment
apiVersion: apps/v1
metadata:
  name: cvsite
spec:
  selector:
    matchLabels:
      app: cvsite
  replicas: 2
  template:
    metadata:
      labels:
        app: cvsite
    spec:
      containers:
        - name: cvsite
          image: mhemeryck/cvsite:latest
---
kind: Service
apiVersion: v1
metadata:
  name: cvsite
  labels:
    app: cvsite
spec:
  type: ClusterIP
  selector:
    app: cvsite
  ports:
    - name: web
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: cvsite
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: cvsite
              servicePort: 80
